"""empty message

Revision ID: 4eb54495cc6a
Revises: 
Create Date: 2020-09-02 17:02:55.398144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb54495cc6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=225), nullable=True),
    sa.Column('password', sa.String(length=225), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    op.create_table('family_input',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=225), nullable=False),
    sa.Column('image', sa.String(length=225), nullable=True),
    sa.Column('father', sa.String(length=225), nullable=True),
    sa.Column('mother', sa.String(length=225), nullable=True),
    sa.Column('spouse', sa.String(length=225), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family_input')
    op.drop_table('users')
    # ### end Alembic commands ###
